Repository extinctsion/Hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#10 Added selection sort algorithm to repo: using java
  Java/selection sort algorithm.java
Labels: hacktoberfest-accepted

#12 Rotate Image
  Java/Rotate_Image.java
Labels: hacktoberfest-accepted

#14 Create TowerofHanoi
  Java/TowerofHanoi
Labels: enhancement, hacktoberfest-accepted

#13 Generate Parentheses
  Java/Generate_Parentheses.java
Labels: hacktoberfest-accepted

#15 Create SelectionSort
  Java/SelectionSort
Labels: hacktoberfest-accepted

#17 Create AllSortingAlgorithms.cpp
  CPP/AllSortingAlgorithms.cpp
Labels: hacktoberfest-accepted

#21 Radix Sort in java
  Java/Radix sort.java
Labels: hacktoberfest-accepted

#20 Create longestCommonPrefix.java
  Java/longestCommonPrefix.java
Labels: hacktoberfest-accepted

#19 Create HeapSort.java
  Java/HeapSort.java
Labels: hacktoberfest-accepted

#18 Create SelectionSort
  SelectionSort
Labels: hacktoberfest-accepted

#16 By using sql created calculator through procedure
  SQL/Calculator.sql
Labels: hacktoberfest-accepted

#22 Created Turtle.py
  Python/Turtle.py
Labels: hacktoberfest-accepted

#25 Create checkstringsanagram.java
  Java/checkstringsanagram.java
Labels: hacktoberfest-accepted

#31 Bmi Calculator in python
  Python/Bmi calculator.py
Labels: hacktoberfest-accepted

#37 Create RadixSort.cpp
  CPP/RadixSort.cpp
Labels: good first issue, hacktoberfest-accepted

#33 Added PriorityQueue.java file
  Java/PriorityQueue.java
Labels: hacktoberfest-accepted

#32 Added PrimeNumbersASFreq.cpp CPP solution
  CPP/PrimeNumbersASFreq.cpp
Labels: hacktoberfest-accepted

#50 Added a java and cpp program
  CPP/Caesar_Cipher_Encode.cpp
  Java/CaesarCipher.class
  Java/CaesarCipher.java
  content/participant/subhro1530.md
  static/subhro1530.jpg
Labels: hacktoberfest-accepted, hacktoberfest2023

#47 added fb_logo in turtle
  Python/fb_logo.py
Labels: hacktoberfest-accepted

#59 Add qr-code-generator
  React Native/qr-code-generator-mobile-app/App.js
  React Native/qr-code-generator-mobile-app/app.json
  React Native/qr-code-generator-mobile-app/assets/YB.png
  React Native/qr-code-generator-mobile-app/assets/adaptive-icon.png
  React Native/qr-code-generator-mobile-app/assets/app-logo.png
  React Native/qr-code-generator-mobile-app/assets/favicon.png
  React Native/qr-code-generator-mobile-app/assets/icon.png
  React Native/qr-code-generator-mobile-app/assets/splash.png
  React Native/qr-code-generator-mobile-app/babel.config.js
  React Native/qr-code-generator-mobile-app/eas.json
  React Native/qr-code-generator-mobile-app/package-lock.json
  React Native/qr-code-generator-mobile-app/package.json
Labels: hacktoberfest-accepted, hacktoberfest2023

#60 Added LeapYearChecker and BubbleSort
  Python/BubbleSort.py
  Python/LeapYearChecker.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#23 feat: Added GFG Challenges
  CPP/Addition_square_matrices.cpp
  CPP/Alternative_positive_negative.cpp
  CPP/Anagram.cpp
  CPP/Armstrong_number.cpp
  CPP/Array_subset.cpp
  CPP/Arrays_sum.cpp
  CPP/At_least_two_greater_elements.cpp
  CPP/Average_stream.cpp
  CPP/Binary_Search.cpp
  CPP/Check_Binary.cpp
  CPP/Check_String.cpp
  CPP/Check_if_Two_Array_are_equal.cpp
  CPP/Check_kth_bit.cpp
  CPP/Complete_the_skills.cpp
  CPP/Compound_Interest.cpp
  CPP/Convert_String_to_LowerCase.cpp
  CPP/Convert_list_of_character_into_string.cpp
  CPP/Count_Digits.cpp
  CPP/Count_camel.cpp
  CPP/Count_type_Characters.cpp
  CPP/Cube_root_number.cpp
  CPP/Cyclically_rotate_an_array_by_one.cpp
  CPP/Delete_Node.cpp
  CPP/Delete_alternate_characters.cpp
Labels: hacktoberfest-accepted

#28 Create Heap_Sort.java
  Java/Heap_Sort.java
Labels: help wanted, hacktoberfest-accepted

#36 Create Detect LinkedList Cycle
  Java/Detect LinkedList Cycle .java
Labels: duplicate, hacktoberfest-accepted

#39 Heap_sort.java
  Heap_sort.java
Labels: hacktoberfest-accepted

#43 Create Maximumreversedrubarraypob.java
  Java/MaximumReversedSubarray.java
Labels: hacktoberfest-accepted

#45 Create UniqueMinimumProductSubarra.java
  Java/UniqueMinimumProductSubarra.java
Labels: hacktoberfest-accepted

#62 Resolved Java bugs in altpos&neg , Palindrome and Commonelements
  Java/Alternatepositiveandnegativenumbers.java
  Java/Commonelements.java
  Java/Palindrome.java
Labels: hacktoberfest-accepted, hacktoberfest2023

#64 feat: Implement Shell Sort Algorithm in TypeScript
  TypeScript/ShellSort.ts
Labels: hacktoberfest-accepted, hacktoberfest2023

#49 BFSDFS.cpp
  CPP/bfsdfs.cpp
Labels: duplicate, hacktoberfest-accepted, hacktoberfest2023

#56 Create permutation.cpp
  CPP/permutation.cpp
Labels: hacktoberfest-accepted, hacktoberfest2023

#75 Create simple_text_editor.py
  Python/simple_text_editor.py
Labels: hacktoberfest-accepted, hacktoberfest2023

#84 Create UserLoginInterface.py
  Python/UserLoginInterface.py
Labels: hacktoberfest-accepted, hacktoberfest2023
